import { Platform } from "react-native";

export const BrandColors = {
  primary: "#5638F5",
  primaryPressed: "#4329D9",
  primarySoft: "#EEF1FF",
  primaryBorder: "#9BA8FF",
  secondary: "#2F80ED",
  accentPurple: "#A020F0",
  aiBlue: "#0B57FF",
  success: "#00C853",
  successSoft: "#EAFBF1",
  warning: "#FF4B00",
  warningSoft: "#FFF6E8",
  danger: "#FF2D3D",
  dangerSoft: "#FFE6EA",
  food: "#FF2D3D",
  transport: "#2F80ED",
  bills: "#00C853",
  shopping: "#F5B400",
  others: "#9CA3AF",
  chartLine: "#6266F1",
} as const;

export const NeutralColors = {
  white: "#FFFFFF",
  black: "#000000",
  gray25: "#FCFCFD",
  gray50: "#F9FAFB",
  gray100: "#F3F4F6",
  gray150: "#EEF0F4",
  gray200: "#E5E7EB",
  gray300: "#D1D5DB",
  gray400: "#9CA3AF",
  gray500: "#6B7280",
  gray600: "#4B5563",
  gray700: "#374151",
  gray800: "#1F2937",
  gray900: "#111827",
  gray950: "#0B1020",
} as const;

export const Colors = {
  light: {
    brand: BrandColors.primary,
    primary: BrandColors.primary,
    primaryPressed: BrandColors.primaryPressed,
    primarySoft: BrandColors.primarySoft,
    secondary: BrandColors.secondary,
    accent: BrandColors.accentPurple,
    ai: BrandColors.aiBlue,
    success: BrandColors.success,
    warning: BrandColors.warning,
    danger: BrandColors.danger,
    text: NeutralColors.gray900,
    textSecondary: NeutralColors.gray500,
    textMuted: NeutralColors.gray400,
    background: NeutralColors.gray50,
    surface: NeutralColors.white,
    surfaceMuted: NeutralColors.gray100,
    card: NeutralColors.white,
    cardElevated: NeutralColors.white,
    border: NeutralColors.gray200,
    borderStrong: NeutralColors.gray300,
    input: NeutralColors.gray50,
    inputBorder: NeutralColors.gray300,
    tint: BrandColors.primary,
    icon: NeutralColors.gray500,
    tabBar: NeutralColors.white,
    tabIconDefault: NeutralColors.gray500,
    tabIconSelected: BrandColors.primary,
    shadow: NeutralColors.black,
    progressTrack: "#8E54EF",
    progressFill: NeutralColors.black,
    chartGrid: "#F1F3F7",
    aiCard: "#EAF3FF",
    successCard: BrandColors.successSoft,
    warningCard: BrandColors.warningSoft,
    dangerCard: BrandColors.dangerSoft,
  },
  dark: {
    brand: "#7C67FF",
    primary: "#7C67FF",
    primaryPressed: "#9B8BFF",
    primarySoft: "#211D45",
    secondary: "#6EA8FF",
    accent: "#C084FC",
    ai: "#7DB1FF",
    success: "#4ADE80",
    warning: "#FF8A3D",
    danger: "#FF5A67",
    text: "#F7F7FB",
    textSecondary: "#B7BDCB",
    textMuted: "#7E8798",
    background: "#0B1020",
    surface: "#12182A",
    surfaceMuted: "#1A2236",
    card: "#151D31",
    cardElevated: "#1B2540",
    border: "#273149",
    borderStrong: "#35405C",
    input: "#101729",
    inputBorder: "#35405C",
    tint: "#7C67FF",
    icon: "#B7BDCB",
    tabBar: "#111827",
    tabIconDefault: "#8B93A5",
    tabIconSelected: "#8B7BFF",
    shadow: NeutralColors.black,
    progressTrack: "#2E245A",
    progressFill: "#7C67FF",
    chartGrid: "#202A40",
    aiCard: "#122747",
    successCard: "#0E2B1D",
    warningCard: "#331F0E",
    dangerCard: "#35151B",
  },
};

export const CategoryColors = {
  food: BrandColors.food,
  transport: BrandColors.transport,
  bills: BrandColors.bills,
  shopping: BrandColors.shopping,
  others: BrandColors.others,
} as const;

export const Gradients = {
  primaryCard: [BrandColors.primary, BrandColors.accentPurple],
  darkPrimaryCard: ["#4C35D8", "#7B1FEA"],
} as const;

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: "system-ui",
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: "ui-serif",
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: "ui-rounded",
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
